[2025-07-30T14:36:03.448+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:36:03.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:36:03.452+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:36:03.452+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:36:04.727+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:36:04.722+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:36:04.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:36:04.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 1.306 seconds
[2025-07-30T14:36:35.952+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:36:35.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:36:35.957+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:36:35.957+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:36:35.987+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:36:35.982+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:36:35.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:36:36.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.079 seconds
[2025-07-30T14:37:06.787+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:37:06.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:37:06.791+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:37:06.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:37:06.820+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:37:06.815+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:37:06.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:37:06.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.073 seconds
[2025-07-30T14:37:37.238+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:37:37.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:37:37.241+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:37:37.241+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:37:37.272+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:37:37.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:37:37.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:37:37.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.065 seconds
[2025-07-30T14:38:07.450+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:38:07.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:38:07.453+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:38:07.453+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:38:07.485+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:38:07.480+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:38:07.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:38:07.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.061 seconds
[2025-07-30T14:38:37.668+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:38:37.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:38:37.671+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:38:37.670+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:38:37.713+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:38:37.705+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:38:37.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:38:37.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.081 seconds
[2025-07-30T14:39:08.072+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:39:08.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:39:08.077+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:39:08.077+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:39:08.128+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:39:08.121+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:39:08.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:39:08.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.101 seconds
[2025-07-30T14:39:39.370+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:39:39.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:39:39.375+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:39:39.374+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:39:39.400+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:39:39.396+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:39:39.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:39:39.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.061 seconds
[2025-07-30T14:40:10.023+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:40:10.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:40:10.026+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:40:10.026+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:40:10.052+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:40:10.048+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:40:10.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:40:10.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.060 seconds
[2025-07-30T14:40:40.330+0000] {processor.py:161} INFO - Started process (PID=486) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:40:40.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:40:40.334+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:40:40.333+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:40:40.364+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:40:40.358+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:40:40.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:40:40.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.070 seconds
[2025-07-30T14:44:10.040+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:44:10.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:44:10.045+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:44:10.044+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:44:11.225+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:44:11.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:44:11.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:44:11.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 1.222 seconds
[2025-07-30T14:44:42.351+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:44:42.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:44:42.354+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:44:42.354+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:44:42.381+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:44:42.376+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:44:42.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:44:42.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.055 seconds
[2025-07-30T14:45:12.872+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:45:12.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:45:12.875+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:45:12.875+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:45:12.901+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:45:12.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:45:12.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:45:12.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.057 seconds
[2025-07-30T14:45:42.999+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:45:43.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:45:43.002+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:45:43.002+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:45:43.031+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:45:43.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:45:43.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:45:43.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.058 seconds
[2025-07-30T14:46:13.367+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:46:13.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:46:13.371+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:46:13.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:46:13.413+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:46:13.405+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:46:13.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:46:13.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.079 seconds
[2025-07-30T14:46:44.085+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:46:44.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:46:44.163+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:46:44.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:46:44.443+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:46:44.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:46:44.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:46:45.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 1.220 seconds
[2025-07-30T14:47:17.755+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:47:17.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:47:17.758+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:47:17.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:47:18.953+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:47:18.947+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:47:18.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:47:18.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 1.231 seconds
[2025-07-30T14:47:50.254+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:47:50.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:47:50.268+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:47:50.268+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:47:50.311+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:47:50.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:47:50.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:47:50.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.115 seconds
[2025-07-30T14:48:20.806+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:48:20.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:48:20.809+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:48:20.809+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:48:20.836+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:48:20.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:48:20.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:48:20.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.061 seconds
[2025-07-30T14:48:50.941+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:48:50.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:48:50.946+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:48:50.946+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:48:50.976+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:48:50.970+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:48:50.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:48:51.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.078 seconds
[2025-07-30T14:49:23.392+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:49:23.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:49:23.402+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:49:23.401+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:49:23.453+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:49:23.443+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:49:23.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:49:23.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.174 seconds
[2025-07-30T14:49:55.850+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:49:55.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:49:55.855+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:49:55.855+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:49:55.897+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:49:55.890+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:49:55.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:49:55.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.095 seconds
[2025-07-30T14:50:28.297+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:50:28.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:50:28.300+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:50:28.300+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:50:28.325+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:50:28.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:50:28.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:50:28.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.055 seconds
[2025-07-30T14:50:59.038+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:50:59.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:50:59.042+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:50:59.042+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:50:59.071+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:50:59.066+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:50:59.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:50:59.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.067 seconds
[2025-07-30T14:51:37.764+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:51:37.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:51:37.780+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:51:37.779+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:51:38.151+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:51:38.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:51:38.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:51:38.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.434 seconds
[2025-07-30T14:52:09.008+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:52:09.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:52:09.020+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:52:09.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:52:09.064+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:52:09.056+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:52:09.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:52:09.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.115 seconds
[2025-07-30T14:52:39.555+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:52:39.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:52:39.560+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:52:39.559+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:52:39.600+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:52:39.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:52:39.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:52:39.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.104 seconds
[2025-07-30T14:54:10.379+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:54:10.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:54:10.383+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:54:10.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:54:11.484+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:54:11.477+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:54:11.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:54:11.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 1.137 seconds
[2025-07-30T14:54:41.718+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:54:41.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:54:41.724+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:54:41.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:54:41.749+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:54:41.744+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:54:41.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:54:41.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.065 seconds
[2025-07-30T14:55:12.205+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:55:12.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:55:12.209+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:55:12.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:55:12.232+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:55:12.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:55:12.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:55:12.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.060 seconds
[2025-07-30T14:55:42.485+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:55:42.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:55:42.495+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:55:42.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:55:42.552+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:55:42.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:55:42.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:55:42.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.145 seconds
[2025-07-30T14:56:12.787+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:12.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:56:12.790+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:56:12.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:12.816+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:56:12.812+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/cleaning/day_clean.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cleaning/day_clean.py", line 4, in <module>
    df = pd.read_csv('/opt/airflow/dags/data/day.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/day.csv'
[2025-07-30T14:56:12.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:12.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.054 seconds
[2025-07-30T14:56:19.333+0000] {processor.py:161} INFO - Started process (PID=347) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:19.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:56:19.336+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:56:19.335+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:19.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:19.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.047 seconds
[2025-07-30T14:56:33.118+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:33.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:56:33.121+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:56:33.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:33.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:56:33.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.040 seconds
[2025-07-30T14:57:03.266+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:57:03.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:57:03.268+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:57:03.268+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:57:03.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:57:03.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.032 seconds
[2025-07-30T14:57:47.948+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:57:47.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:57:47.956+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:57:47.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:57:48.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:57:48.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.497 seconds
[2025-07-30T14:58:19.355+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:58:19.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:58:19.362+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:58:19.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:58:19.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:58:19.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.055 seconds
[2025-07-30T14:58:49.866+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:58:49.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:58:49.870+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:58:49.870+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:58:49.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:58:49.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.046 seconds
[2025-07-30T14:59:20.748+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:59:20.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:59:20.758+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:59:20.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:59:20.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:59:20.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.078 seconds
[2025-07-30T14:59:51.454+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:59:51.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T14:59:51.461+0000] {logging_mixin.py:188} INFO - [2025-07-30T14:59:51.460+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:59:51.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T14:59:51.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.065 seconds
[2025-07-30T15:00:21.878+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:00:21.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:00:21.883+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:00:21.883+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:00:21.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:00:21.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.057 seconds
[2025-07-30T15:00:52.457+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:00:52.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:00:52.459+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:00:52.459+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:00:52.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:00:52.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.033 seconds
[2025-07-30T15:01:22.668+0000] {processor.py:161} INFO - Started process (PID=485) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:01:22.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:01:22.671+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:01:22.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:01:22.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:01:22.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.038 seconds
[2025-07-30T15:01:52.980+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:01:52.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:01:52.984+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:01:52.983+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:01:52.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:01:53.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.042 seconds
[2025-07-30T15:02:23.307+0000] {processor.py:161} INFO - Started process (PID=555) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:02:23.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:02:23.311+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:02:23.310+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:02:23.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:02:23.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.038 seconds
[2025-07-30T15:02:55.816+0000] {processor.py:161} INFO - Started process (PID=590) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:02:55.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:02:55.819+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:02:55.819+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:02:55.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:02:55.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.044 seconds
[2025-07-30T15:03:28.008+0000] {processor.py:161} INFO - Started process (PID=625) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:03:28.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:03:28.011+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:03:28.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:03:28.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:03:28.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.036 seconds
[2025-07-30T15:03:58.738+0000] {processor.py:161} INFO - Started process (PID=675) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:03:58.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:03:58.742+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:03:58.742+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:03:58.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:03:58.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.038 seconds
[2025-07-30T15:04:29.067+0000] {processor.py:161} INFO - Started process (PID=710) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:04:29.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:04:29.071+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:04:29.070+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:04:29.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:04:29.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.034 seconds
[2025-07-30T15:05:06.786+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:05:06.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:05:06.798+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:05:06.797+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:05:07.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:05:07.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.697 seconds
[2025-07-30T15:05:38.174+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:05:38.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:05:38.177+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:05:38.177+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:05:38.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:05:38.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.040 seconds
[2025-07-30T15:06:09.014+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:06:09.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:06:09.023+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:06:09.023+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:06:09.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:06:09.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.059 seconds
[2025-07-30T15:06:42.583+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:06:42.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:06:42.586+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:06:42.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:06:42.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:06:42.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.034 seconds
[2025-07-30T15:07:13.258+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:07:13.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:07:13.261+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:07:13.261+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:07:13.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:07:13.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.032 seconds
[2025-07-30T15:07:43.568+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:07:43.569+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:07:43.572+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:07:43.571+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:07:43.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:07:43.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.044 seconds
[2025-07-30T15:08:13.739+0000] {processor.py:161} INFO - Started process (PID=412) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:08:13.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:08:13.743+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:08:13.742+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:08:13.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:08:13.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.041 seconds
[2025-07-30T15:08:44.528+0000] {processor.py:161} INFO - Started process (PID=447) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:08:44.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:08:44.538+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:08:44.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:08:44.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:08:44.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.072 seconds
[2025-07-30T15:09:15.592+0000] {processor.py:161} INFO - Started process (PID=482) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:09:15.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:09:15.597+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:09:15.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:09:15.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:09:15.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.053 seconds
[2025-07-30T15:09:45.923+0000] {processor.py:161} INFO - Started process (PID=517) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:09:45.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:09:45.926+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:09:45.926+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:09:45.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:09:45.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.041 seconds
[2025-07-30T15:10:16.215+0000] {processor.py:161} INFO - Started process (PID=552) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:10:16.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:10:16.219+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:10:16.218+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:10:16.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:10:16.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.037 seconds
[2025-07-30T15:10:47.234+0000] {processor.py:161} INFO - Started process (PID=587) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:10:47.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:10:47.237+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:10:47.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:10:47.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:10:47.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.033 seconds
[2025-07-30T15:11:17.478+0000] {processor.py:161} INFO - Started process (PID=622) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:11:17.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:11:17.481+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:11:17.481+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:11:17.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:11:17.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.036 seconds
[2025-07-30T15:11:48.540+0000] {processor.py:161} INFO - Started process (PID=657) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:11:48.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:11:48.543+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:11:48.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:11:48.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:11:48.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.035 seconds
[2025-07-30T15:12:18.773+0000] {processor.py:161} INFO - Started process (PID=692) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:12:18.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:12:18.777+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:12:18.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:12:18.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:12:18.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.043 seconds
[2025-07-30T15:12:48.904+0000] {processor.py:161} INFO - Started process (PID=727) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:12:48.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:12:48.907+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:12:48.907+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:12:48.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:12:48.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.054 seconds
[2025-07-30T15:13:19.462+0000] {processor.py:161} INFO - Started process (PID=762) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:13:19.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:13:19.473+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:13:19.471+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:13:19.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:13:19.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.086 seconds
[2025-07-30T15:13:50.252+0000] {processor.py:161} INFO - Started process (PID=797) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:13:50.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:13:50.256+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:13:50.255+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:13:50.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:13:50.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.042 seconds
[2025-07-30T15:14:20.854+0000] {processor.py:161} INFO - Started process (PID=832) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:14:20.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:14:20.857+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:14:20.857+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:14:20.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:14:20.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.044 seconds
[2025-07-30T15:14:51.222+0000] {processor.py:161} INFO - Started process (PID=867) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:14:51.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:14:51.229+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:14:51.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:14:51.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:14:51.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.096 seconds
[2025-07-30T15:15:21.779+0000] {processor.py:161} INFO - Started process (PID=902) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:15:21.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:15:21.783+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:15:21.782+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:15:21.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:15:21.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.112 seconds
[2025-07-30T15:15:54.118+0000] {processor.py:161} INFO - Started process (PID=937) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:15:54.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:15:54.122+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:15:54.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:15:54.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:15:54.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.051 seconds
[2025-07-30T15:16:26.417+0000] {processor.py:161} INFO - Started process (PID=972) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:16:26.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:16:26.423+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:16:26.422+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:16:26.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:16:26.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.165 seconds
[2025-07-30T15:16:58.860+0000] {processor.py:161} INFO - Started process (PID=1007) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:16:58.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:16:58.863+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:16:58.863+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:16:58.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:16:58.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.036 seconds
[2025-07-30T15:17:31.101+0000] {processor.py:161} INFO - Started process (PID=1042) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:17:31.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:17:31.104+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:17:31.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:17:31.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:17:31.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.037 seconds
[2025-07-30T15:18:03.248+0000] {processor.py:161} INFO - Started process (PID=1077) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:18:03.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:18:03.251+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:18:03.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:18:03.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:18:03.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.036 seconds
[2025-07-30T15:18:33.895+0000] {processor.py:161} INFO - Started process (PID=1112) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:18:33.896+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:18:33.898+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:18:33.898+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:18:33.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:18:33.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.032 seconds
[2025-07-30T15:19:04.228+0000] {processor.py:161} INFO - Started process (PID=1147) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:19:04.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:19:04.230+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:19:04.230+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:19:04.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:19:04.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.037 seconds
[2025-07-30T15:19:34.715+0000] {processor.py:161} INFO - Started process (PID=1182) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:19:34.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:19:34.719+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:19:34.719+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:19:34.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:19:34.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.054 seconds
[2025-07-30T15:20:04.918+0000] {processor.py:161} INFO - Started process (PID=1217) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:20:04.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:20:04.921+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:20:04.921+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:20:04.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:20:04.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.034 seconds
[2025-07-30T15:20:35.080+0000] {processor.py:161} INFO - Started process (PID=1252) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:20:35.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:20:35.083+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:20:35.082+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:20:35.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:20:35.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.032 seconds
[2025-07-30T15:21:05.230+0000] {processor.py:161} INFO - Started process (PID=1287) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:21:05.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:21:05.234+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:21:05.233+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:21:05.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:21:05.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.040 seconds
[2025-07-30T15:21:35.546+0000] {processor.py:161} INFO - Started process (PID=1322) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:21:35.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:21:35.553+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:21:35.553+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:21:35.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:21:35.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.074 seconds
[2025-07-30T15:22:05.891+0000] {processor.py:161} INFO - Started process (PID=1357) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:22:05.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:22:05.894+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:22:05.894+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:22:05.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:22:05.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.037 seconds
[2025-07-30T15:22:36.000+0000] {processor.py:161} INFO - Started process (PID=1392) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:22:36.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:22:36.006+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:22:36.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:22:36.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:22:36.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.070 seconds
[2025-07-30T15:23:06.161+0000] {processor.py:161} INFO - Started process (PID=1432) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:23:06.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:23:06.164+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:23:06.163+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:23:06.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:23:06.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.032 seconds
[2025-07-30T15:23:36.401+0000] {processor.py:161} INFO - Started process (PID=1467) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:23:36.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:23:36.404+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:23:36.404+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:23:36.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:23:36.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.038 seconds
[2025-07-30T15:24:06.574+0000] {processor.py:161} INFO - Started process (PID=1507) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:24:06.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:24:06.577+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:24:06.576+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:24:06.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:24:06.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.036 seconds
[2025-07-30T15:24:36.900+0000] {processor.py:161} INFO - Started process (PID=1542) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:24:36.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:24:36.905+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:24:36.905+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:24:36.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:24:36.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.056 seconds
[2025-07-30T15:25:07.193+0000] {processor.py:161} INFO - Started process (PID=1577) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:25:07.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:25:07.202+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:25:07.201+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:25:07.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:25:07.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.715 seconds
[2025-07-30T15:25:38.817+0000] {processor.py:161} INFO - Started process (PID=1612) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:25:38.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:25:38.872+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:25:38.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:25:38.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:25:39.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.194 seconds
[2025-07-30T15:26:11.322+0000] {processor.py:161} INFO - Started process (PID=1647) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:26:11.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:26:11.325+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:26:11.324+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:26:11.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:26:11.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.039 seconds
[2025-07-30T15:26:43.524+0000] {processor.py:161} INFO - Started process (PID=1682) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:26:43.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:26:43.527+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:26:43.527+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:26:43.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:26:43.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.098 seconds
[2025-07-30T15:27:13.980+0000] {processor.py:161} INFO - Started process (PID=1717) to work on /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:27:13.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cleaning/day_clean.py for tasks to queue
[2025-07-30T15:27:13.995+0000] {logging_mixin.py:188} INFO - [2025-07-30T15:27:13.994+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:27:14.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cleaning/day_clean.py
[2025-07-30T15:27:14.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cleaning/day_clean.py took 0.085 seconds
